# Generated by Django 2.1.1 on 2019-03-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='alias',
            field=models.CharField(default='pesholudia', max_length=255),
            preserve_default=False,
        ),
    ]
