# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0002_auto_20180311_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
