# Generated by Django 2.1.1 on 2019-02-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setup',
            old_name='game',
            new_name='owner',
        ),
    ]
