# Generated by Django 2.1.1 on 2019-08-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionframe',
            old_name='frame',
            new_name='image',
        ),
    ]
