# Generated by Django 2.1.1 on 2019-08-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('from_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Style')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
                ('to_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Style')),
            ],
        ),
        migrations.CreateModel(
            name='Handler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=255)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='api.Expression')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='api.Expression')),
            ],
        ),
    ]
