# Generated by Django 2.1.1 on 2019-04-23 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='board',
        ),
        migrations.RemoveField(
            model_name='path',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='path',
            name='done',
        ),
        migrations.RemoveField(
            model_name='path',
            name='risk',
        ),
        migrations.RemoveField(
            model_name='path',
            name='undone',
        ),
        migrations.AddField(
            model_name='path',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Field'),
        ),
        migrations.AddField(
            model_name='path',
            name='setups',
            field=models.ManyToManyField(blank=True, related_name='setups_paths', to='api.Setup'),
        ),
    ]
