# Generated by Django 2.1.1 on 2019-08-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='game',
        ),
        migrations.RemoveField(
            model_name='group',
            name='image',
        ),
        migrations.RemoveField(
            model_name='groupitem',
            name='action',
        ),
        migrations.RemoveField(
            model_name='groupitem',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='groupitem',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='groupitem',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='groupitem',
            name='disable',
        ),
        migrations.RemoveField(
            model_name='groupitem',
            name='enable',
        ),
        migrations.RemoveField(
            model_name='groupitem',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupitem',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='groupitem',
            name='setups',
        ),
        migrations.RemoveField(
            model_name='groupitem',
            name='token',
        ),
        migrations.RemoveField(
            model_name='source',
            name='game',
        ),
        migrations.RemoveField(
            model_name='source',
            name='group',
        ),
        migrations.RemoveField(
            model_name='source',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='draw',
        ),
        migrations.RemoveField(
            model_name='token',
            name='attributes',
        ),
        migrations.AlterField(
            model_name='action',
            name='cost',
            field=models.ManyToManyField(blank=True, related_name='cost_actions', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='action',
            name='done',
            field=models.ManyToManyField(blank=True, related_name='done_actions', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='action',
            name='reveal_cost',
            field=models.ManyToManyField(blank=True, related_name='reveal_cost_actions', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='action',
            name='undone',
            field=models.ManyToManyField(blank=True, related_name='undone_actions', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='cost',
            field=models.ManyToManyField(blank=True, related_name='cost_choices', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='done',
            field=models.ManyToManyField(blank=True, related_name='done_choices', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='reveal_cost',
            field=models.ManyToManyField(blank=True, related_name='reveal_cost_choices', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='undone',
            field=models.ManyToManyField(blank=True, related_name='undone_choices', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='effect',
            field=models.ManyToManyField(blank=True, to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='cost',
            field=models.ManyToManyField(blank=True, related_name='cost_conditions', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='done',
            field=models.ManyToManyField(blank=True, related_name='done_conditions', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='reveal_cost',
            field=models.ManyToManyField(blank=True, related_name='reveal_cost_conditions', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='undone',
            field=models.ManyToManyField(blank=True, related_name='undone_conditions', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='field',
            name='cost',
            field=models.ManyToManyField(blank=True, related_name='cost_fields', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='field',
            name='done',
            field=models.ManyToManyField(blank=True, related_name='done_fields', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='field',
            name='risk',
            field=models.ManyToManyField(blank=True, related_name='risk_fields', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='field',
            name='undone',
            field=models.ManyToManyField(blank=True, related_name='undone_fields', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='round',
            name='done',
            field=models.ManyToManyField(blank=True, related_name='done_rounds', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='round',
            name='undone',
            field=models.ManyToManyField(blank=True, related_name='undone_rounds', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='token',
            name='cost',
            field=models.ManyToManyField(blank=True, related_name='cost_tokens', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='token',
            name='reveal_cost',
            field=models.ManyToManyField(blank=True, related_name='reveal_cost_tokens', to='api.Expression'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupItem',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
