# Generated by Django 2.1.1 on 2020-01-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='style',
            old_name='background_color',
            new_name='fill',
        ),
    ]
