# Generated by Django 2.1.1 on 2019-05-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='radius',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
