# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='maps')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Game')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='boardType',
            field=models.CharField(choices=[('MAP', 'MAP'), ('BASIC_GRID', 'BASIC_GRID')], max_length=255),
        ),
    ]
