# Generated by Django 2.1.1 on 2019-04-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='fill',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='height',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='shape',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='strokeColor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='strokeThickness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='width',
            field=models.TextField(blank=True, null=True),
        ),
    ]
