# Generated by Django 2.1.1 on 2019-08-14 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phaseslot',
            name='done',
        ),
        migrations.RemoveField(
            model_name='roundslot',
            name='done',
        ),
        migrations.AddField(
            model_name='phase',
            name='display_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='done',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Expression'),
        ),
        migrations.AddField(
            model_name='round',
            name='display_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='done',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Expression'),
        ),
        migrations.AddField(
            model_name='setup',
            name='display_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
