# Generated by Django 2.1.1 on 2019-08-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='board',
        ),
        migrations.AddField(
            model_name='faction',
            name='stages',
            field=models.ManyToManyField(blank=True, related_name='stages_factions', to='api.Stage'),
        ),
    ]
