# Generated by Django 2.1.1 on 2018-12-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_path_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='points',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='shape',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
