# Generated by Django 2.1.1 on 2018-11-05 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_field_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='stage',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='poolitem',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='poolitem',
            name='token',
        ),
        migrations.RemoveField(
            model_name='token',
            name='start',
        ),
        migrations.AddField(
            model_name='action',
            name='unlimited',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conditionclause',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Phase'),
        ),
        migrations.AddField(
            model_name='location',
            name='allowed',
            field=models.ManyToManyField(blank=True, related_name='allowed', to='api.Stack'),
        ),
        migrations.AddField(
            model_name='location',
            name='restricted',
            field=models.ManyToManyField(blank=True, to='api.Stack'),
        ),
        migrations.AddField(
            model_name='location',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Token'),
        ),
        migrations.AddField(
            model_name='token',
            name='cost',
            field=models.ManyToManyField(blank=True, related_name='token_cost', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='location',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Field'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='mode',
            field=models.TextField(choices=[('DRAW', 'DRAW'), ('AUTO', 'AUTO')], default='DRAW'),
        ),
        migrations.AlterField(
            model_name='round',
            name='condition',
            field=models.ManyToManyField(related_name='round_condition', to='api.Stack'),
        ),
    ]
