# Generated by Django 2.1.1 on 2019-08-18 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190818_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_choiceframes', to='api.ImageAsset')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='api.Choice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
