# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171108_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='field_images')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='boardType',
            field=models.CharField(choices=[('TERRITORY_MAP', 'TERRITORY_MAP'), ('BASIC_GRID', 'BASIC_GRID')], max_length=255),
        ),
        migrations.AddField(
            model_name='boardfield',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game'),
        ),
    ]
