# Generated by Django 2.1.1 on 2019-08-11 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_animation_handler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Expression'),
        ),
    ]
