# Generated by Django 2.1.1 on 2019-04-22 12:32

import api.helpers.custom_file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='file',
            field=api.helpers.custom_file.ContentTypeRestrictedFileField(default=1, upload_to='sounds'),
            preserve_default=False,
        ),
    ]
