# Generated by Django 2.1.1 on 2019-08-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190824_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='stages',
        ),
        migrations.AddField(
            model_name='faction',
            name='slots',
            field=models.ManyToManyField(blank=True, related_name='slotss_factions', to='api.Slot'),
        ),
    ]
