# Generated by Django 2.1.1 on 2019-02-16 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190216_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setups', to='api.Game'),
        ),
    ]
