# Generated by Django 2.1.1 on 2019-04-23 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190423_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_paths', to='api.Style'),
        ),
    ]
