# Generated by Django 2.1.1 on 2019-04-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190421_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='height',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='points',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='width',
        ),
    ]
