# Generated by Django 2.1.1 on 2019-08-17 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_slothandler_slotitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='field',
        ),
        migrations.AddField(
            model_name='slot',
            name='display_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_display_text', to='api.Expression'),
        ),
        migrations.AddField(
            model_name='slot',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_slots', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handler_effect', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_handlers', to='api.Expression'),
        ),
    ]
