# Generated by Django 2.1.1 on 2020-06-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200611_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='style',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='widget',
            name='style_inline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
