# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171113_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardfield',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='field_images'),
        ),
    ]
