# Generated by Django 2.1.1 on 2020-01-22 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200120_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.TextField(blank=True, null=True)),
                ('style_inline', models.TextField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_stageframes', to='api.ImageAsset')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='api.Stage')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_stageframes', to='api.Stage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='slotframe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slotframe',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='slotframe',
            name='stage',
        ),
        migrations.DeleteModel(
            name='SlotFrame',
        ),
    ]
