# Generated by Django 2.1.1 on 2019-08-18 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_choiceframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ImageAsset'),
        ),
    ]
