# Generated by Django 2.1.1 on 2019-08-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tokenframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice_scope', to='api.Expression'),
        ),
        migrations.AddField(
            model_name='expression',
            name='preload_as',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
