# Generated by Django 2.1.1 on 2019-08-17 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190817_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='token',
            name='disable',
        ),
        migrations.RemoveField(
            model_name='token',
            name='enable',
        ),
        migrations.RemoveField(
            model_name='token',
            name='reveal_cost',
        ),
        migrations.RemoveField(
            model_name='token',
            name='reveal_slots',
        ),
        migrations.AddField(
            model_name='team',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Expression'),
        ),
        migrations.AddField(
            model_name='token',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_tokens', to='api.Keyword'),
        ),
    ]
