# Generated by Django 2.1.1 on 2019-08-26 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190825_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='populate_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Expression'),
        ),
    ]
