# Generated by Django 2.1.1 on 2020-06-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200611_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgetnode',
            name='x',
        ),
        migrations.RemoveField(
            model_name='widgetnode',
            name='y',
        ),
    ]
