# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171113_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='maps'),
        ),
    ]
