# Generated by Django 2.1.1 on 2019-04-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sound_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ImageAsset')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Keyword')),
                ('keywords', models.ManyToManyField(blank=True, related_name='keywords_states', to='api.Keyword')),
                ('sound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sound')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Style')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
