# Generated by Django 2.1.1 on 2018-11-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181105_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='unlimited',
        ),
        migrations.AddField(
            model_name='action',
            name='limit',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
