# Generated by Django 2.1.1 on 2019-05-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_path_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='disable',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='enable',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='style',
            name='fill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='strokeColor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='strokeThickness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
