# Generated by Django 2.1.1 on 2018-10-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181013_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='effectgroup',
            name='items',
            field=models.ManyToManyField(related_name='effect_group_items', to='api.EffectGroup'),
        ),
    ]
