# Generated by Django 2.1.1 on 2019-08-11 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190811_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='from_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_style', to='api.Style'),
        ),
        migrations.AlterField(
            model_name='animation',
            name='to_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_style', to='api.Style'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effect', to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to='api.Expression'),
        ),
    ]
