# Generated by Django 2.1.1 on 2019-04-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190413_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='keywords',
        ),
        migrations.AddField(
            model_name='action',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_actions', to='api.Keyword'),
        ),
        migrations.RemoveField(
            model_name='choice',
            name='keywords',
        ),
        migrations.AddField(
            model_name='choice',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_choices', to='api.Keyword'),
        ),
        migrations.RemoveField(
            model_name='condition',
            name='keywords',
        ),
        migrations.AddField(
            model_name='condition',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_conditions', to='api.Keyword'),
        ),
        migrations.RemoveField(
            model_name='faction',
            name='keywords',
        ),
        migrations.AddField(
            model_name='faction',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_factions', to='api.Keyword'),
        ),
        migrations.RemoveField(
            model_name='field',
            name='keywords',
        ),
        migrations.AddField(
            model_name='field',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_fields', to='api.Keyword'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='keywords',
        ),
        migrations.AddField(
            model_name='group',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_groups', to='api.Keyword'),
        ),
        migrations.RemoveField(
            model_name='groupitem',
            name='keywords',
        ),
        migrations.AddField(
            model_name='groupitem',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_groupitems', to='api.Keyword'),
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='keywords',
        ),
        migrations.AddField(
            model_name='keyword',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_keywords', to='api.Keyword'),
        ),
        migrations.RemoveField(
            model_name='path',
            name='keywords',
        ),
        migrations.AddField(
            model_name='path',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_paths', to='api.Keyword'),
        ),
        migrations.RemoveField(
            model_name='phase',
            name='keywords',
        ),
        migrations.AddField(
            model_name='phase',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_phases', to='api.Keyword'),
        ),
        migrations.RemoveField(
            model_name='round',
            name='keywords',
        ),
        migrations.AddField(
            model_name='round',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_rounds', to='api.Keyword'),
        ),
        migrations.RemoveField(
            model_name='slot',
            name='keywords',
        ),
        migrations.AddField(
            model_name='slot',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_slots', to='api.Keyword'),
        ),
        migrations.RemoveField(
            model_name='source',
            name='keywords',
        ),
        migrations.AddField(
            model_name='source',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_sources', to='api.Keyword'),
        ),
        migrations.RemoveField(
            model_name='stage',
            name='keywords',
        ),
        migrations.AddField(
            model_name='stage',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_stages', to='api.Keyword'),
        ),
        migrations.RemoveField(
            model_name='style',
            name='keywords',
        ),
        migrations.AddField(
            model_name='style',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_styles', to='api.Keyword'),
        ),
        migrations.RemoveField(
            model_name='team',
            name='keywords',
        ),
        migrations.AddField(
            model_name='team',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_teams', to='api.Keyword'),
        ),
        migrations.RemoveField(
            model_name='token',
            name='keywords',
        ),
        migrations.AddField(
            model_name='token',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_tokens', to='api.Keyword'),
        ),
    ]
