# Generated by Django 2.1.1 on 2019-08-17 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190817_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='value',
        ),
        migrations.AddField(
            model_name='token',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Expression'),
        ),
    ]
