# Generated by Django 2.1.1 on 2018-12-29 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_imageasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageasset',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Game'),
            preserve_default=False,
        ),
    ]
