# Generated by Django 2.1.1 on 2020-01-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_style_interactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='z_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
