# Generated by Django 2.1.1 on 2018-12-29 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_imageasset_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageasset',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='api.Game'),
        ),
    ]
