# Generated by Django 2.1.1 on 2019-04-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190413_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='groupitem',
            name='game',
        ),
        migrations.RemoveField(
            model_name='groupitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='groupitem',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='groupitem',
            name='name',
        ),
    ]
