# Generated by Django 2.1.1 on 2019-08-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190817_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='display_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
