# Generated by Django 2.1.1 on 2019-09-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190925_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='opacity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
