# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171113_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplocation',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='maplocation',
            name='left',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='maplocation',
            name='top',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='maplocation',
            name='width',
            field=models.FloatField(),
        ),
    ]
