# Generated by Django 2.1.1 on 2018-10-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181013_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='restriction',
            field=models.ManyToManyField(related_name='condition_restriction', to='api.EffectStack'),
        ),
        migrations.AddField(
            model_name='condition',
            name='trap_mode',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='conditionclause',
            name='at_keyword_round',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conditionclause',
            name='by_keyword_round',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='effectgroup',
            name='quota',
            field=models.CharField(choices=[('REPEATING', 'REPEATING'), ('ONCE', 'ONCE')], default='REPEATING', max_length=255),
        ),
        migrations.RemoveField(
            model_name='action',
            name='restriction',
        ),
        migrations.AddField(
            model_name='action',
            name='restriction',
            field=models.ManyToManyField(related_name='action_restriction', to='api.EffectStack'),
        ),
        migrations.AlterField(
            model_name='effectgroup',
            name='pick',
            field=models.CharField(choices=[('RANDOM', 'RANDOM'), ('CHOICE', 'CHOICE')], default='RANDOM', max_length=255),
        ),
        migrations.AlterField(
            model_name='effectstack',
            name='relation',
            field=models.TextField(choices=[('AND', 'AND'), ('OR', 'OR'), ('NOT', 'NOT')], default='AND'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='resource_images'),
        ),
    ]
