# Generated by Django 2.1.1 on 2020-02-23 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200128_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='image',
        ),
        migrations.AddField(
            model_name='slot',
            name='display_text_inline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Text'),
        ),
    ]
