# Generated by Django 2.1.1 on 2018-10-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181014_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effectgroup',
            name='items',
        ),
        migrations.RemoveField(
            model_name='effectgroupitem',
            name='restriction',
        ),
        migrations.AddField(
            model_name='effectgroupitem',
            name='restriction',
            field=models.ManyToManyField(related_name='effect_item_restriction', to='api.EffectStack'),
        ),
    ]
