# Generated by Django 2.1.1 on 2018-11-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181107_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='location_images'),
        ),
        migrations.AddField(
            model_name='location',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Location name', max_length=255),
            preserve_default=False,
        ),
    ]
