# Generated by Django 2.1.1 on 2019-01-26 09:50

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190125_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageasset',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='svg_images'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
