# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171113_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='map',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Game'),
        ),
        migrations.AlterField(
            model_name='maplocation',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maplocation',
            name='left',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maplocation',
            name='top',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maplocation',
            name='width',
            field=models.IntegerField(),
        ),
    ]
