# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171114_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('fromLoc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.BoardField')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
                ('toLoc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.MapLocation')),
            ],
        ),
    ]
