# Generated by Django 2.1.1 on 2019-08-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190817_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='mode',
        ),
    ]
