# Generated by Django 2.1.1 on 2019-09-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='animation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animation', to='api.Animation'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sound', to='api.Sound'),
        ),
    ]
