# Generated by Django 2.1.1 on 2020-02-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200223_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='style',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='style_inline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
