# Generated by Django 2.1.1 on 2019-01-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190126_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionconfig',
            name='target_type',
        ),
        migrations.AddField(
            model_name='action',
            name='done',
            field=models.ManyToManyField(blank=True, related_name='done_actions', to='api.Source'),
        ),
        migrations.AddField(
            model_name='action',
            name='undone',
            field=models.ManyToManyField(blank=True, related_name='undone_actions', to='api.Source'),
        ),
        migrations.AddField(
            model_name='actionconfig',
            name='dice_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_dice_amount', to='api.Choice'),
        ),
        migrations.AddField(
            model_name='actionconfig',
            name='target_filter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='secret',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='mode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='actionconfig',
            name='computed_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actionconfig',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
