# Generated by Django 2.1.1 on 2019-08-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_action_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='hidden',
            field=models.NullBooleanField(default=False),
        ),
    ]
