# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_mappath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappath',
            name='fromLoc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='from_loc+', to='api.MapLocation'),
        ),
        migrations.AlterField(
            model_name='mappath',
            name='toLoc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='to_loc+', to='api.MapLocation'),
        ),
    ]
