# Generated by Django 2.1.1 on 2019-02-13 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190126_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageasset',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_game', to='api.Game'),
        ),
    ]
