# Generated by Django 2.1.1 on 2019-09-27 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190927_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.IntegerField(blank=True, null=True)),
                ('from_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_style', to='api.Style')),
            ],
        ),
        migrations.RemoveField(
            model_name='animation',
            name='from_style',
        ),
        migrations.RemoveField(
            model_name='animation',
            name='to_style',
        ),
        migrations.AddField(
            model_name='animation',
            name='type',
            field=models.TextField(default='SEQUENCE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animationstep',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.Animation'),
        ),
        migrations.AddField(
            model_name='animationstep',
            name='to_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_style', to='api.Style'),
        ),
    ]
