# Generated by Django 2.1.1 on 2018-10-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181014_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='cost',
            field=models.ManyToManyField(blank=True, null=True, related_name='action_cost', to='api.EffectStack'),
        ),
        migrations.AlterField(
            model_name='action',
            name='limitation',
            field=models.ManyToManyField(blank=True, null=True, related_name='action_limitation', to='api.EffectStack'),
        ),
        migrations.AlterField(
            model_name='action',
            name='restriction',
            field=models.ManyToManyField(blank=True, null=True, related_name='action_restriction', to='api.EffectStack'),
        ),
    ]
