# Generated by Django 2.1.1 on 2020-03-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200229_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='scale',
            field=models.TextField(blank=True, null=True),
        ),
    ]
