# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171114_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappath',
            name='fromLoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_loc+', to='api.MapLocation'),
        ),
        migrations.AlterField(
            model_name='mappath',
            name='toLoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_loc+', to='api.MapLocation'),
        ),
    ]
