# Generated by Django 2.1.1 on 2019-09-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190927_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='animationstep',
            name='easing',
            field=models.CharField(default='LINEAR', max_length=255),
            preserve_default=False,
        ),
    ]
