# Generated by Django 2.1.1 on 2018-10-16 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181014_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionconfig',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='api.Action'),
        ),
    ]
