# Generated by Django 2.1.1 on 2020-04-02 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200402_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentext',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='api.Token'),
        ),
    ]
