# Generated by Django 2.1.1 on 2018-10-20 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181016_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='limitation',
        ),
        migrations.RemoveField(
            model_name='action',
            name='trap_mode',
        ),
        migrations.AddField(
            model_name='action',
            name='condition',
            field=models.ManyToManyField(blank=True, null=True, related_name='action_condition', to='api.EffectStack'),
        ),
        migrations.AddField(
            model_name='action',
            name='mode',
            field=models.CharField(choices=[('TRAP', 'TRAP'), ('TRIGGER', 'TRIGGER'), ('HYBRID', 'HYBRID')], default='TRAP', max_length=255),
        ),
        migrations.AddField(
            model_name='actionconfig',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_config_action', to='api.Action'),
        ),
        migrations.AlterField(
            model_name='effectgroup',
            name='mode',
            field=models.TextField(choices=[('DRAW', 'DRAW'), ('TRIGGER', 'TRIGGER')], default='DRAW'),
        ),
        migrations.RemoveField(
            model_name='effectgroupitem',
            name='cost',
        ),
        migrations.AddField(
            model_name='effectgroupitem',
            name='cost',
            field=models.ManyToManyField(related_name='effect_item_cost', to='api.EffectStack'),
        ),
    ]
