# Generated by Django 2.1.1 on 2019-09-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_animationstep_easing'),
    ]

    operations = [
        migrations.AddField(
            model_name='animationstep',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transition',
            name='prop',
            field=models.CharField(default='state.hovered', max_length=255),
            preserve_default=False,
        ),
    ]
