# Generated by Django 2.1.1 on 2019-08-17 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190817_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='disable',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='done',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='enable',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='reveal_cost',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='reveal_slots',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='undone',
        ),
        migrations.RemoveField(
            model_name='choiceoption',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='choiceoption',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='choiceoption',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='choiceoption',
            name='value',
        ),
        migrations.RemoveField(
            model_name='choiceoption',
            name='effect',
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Expression'),
        ),
    ]
