# Generated by Django 2.1.1 on 2019-09-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190928_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='transitions',
            field=models.ManyToManyField(blank=True, related_name='transitionss_slots', to='api.Transition'),
        ),
    ]
