# Generated by Django 2.1.1 on 2018-10-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181020_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='effectgroup',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='effectgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_images'),
        ),
        migrations.AddField(
            model_name='effectgroup',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='effectgroup',
            name='name',
            field=models.CharField(default='default name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='effectstack',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='effectstack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stack_images'),
        ),
        migrations.AddField(
            model_name='effectstack',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='effectstack',
            name='name',
            field=models.CharField(default='default group name', max_length=255),
            preserve_default=False,
        ),
    ]
