# Generated by Django 2.1.1 on 2020-04-17 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200402_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotLifecycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('effect', models.TextField(blank=True, null=True)),
                ('sound', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='slot',
            name='consume_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='provide_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slothandler',
            name='static_sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Sonata'),
        ),
        migrations.AddField(
            model_name='style',
            name='tint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotlifecycle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lifecycles', to='api.Slot'),
        ),
        migrations.AddField(
            model_name='slotlifecycle',
            name='static_sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Sonata'),
        ),
    ]
