# Generated by Django 2.1.1 on 2019-08-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190817_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionclause',
            name='action',
        ),
        migrations.RemoveField(
            model_name='conditionclause',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='conditionclause',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='conditionclause',
            name='faction',
        ),
        migrations.RemoveField(
            model_name='conditionclause',
            name='field',
        ),
        migrations.RemoveField(
            model_name='conditionclause',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='conditionclause',
            name='path',
        ),
        migrations.RemoveField(
            model_name='conditionclause',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='conditionclause',
            name='round',
        ),
        migrations.RemoveField(
            model_name='conditionclause',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='conditionclause',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='conditionclause',
            name='token',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='board',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='disable',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='done',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='enable',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='reveal_cost',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='reveal_slots',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='undone',
        ),
        migrations.RemoveField(
            model_name='field',
            name='done',
        ),
        migrations.RemoveField(
            model_name='field',
            name='undone',
        ),
        migrations.AddField(
            model_name='condition',
            name='clause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Expression'),
        ),
        migrations.AddField(
            model_name='condition',
            name='fails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fails_conditions', to='api.Expression'),
        ),
        migrations.AddField(
            model_name='condition',
            name='passes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes_conditions', to='api.Expression'),
        ),
        migrations.AddField(
            model_name='field',
            name='fails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fails_fields', to='api.Expression'),
        ),
        migrations.AddField(
            model_name='field',
            name='passes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes_fields', to='api.Expression'),
        ),
        migrations.DeleteModel(
            name='ConditionClause',
        ),
    ]
