# Generated by Django 2.1.1 on 2019-09-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_slot_transitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='animationstep',
            name='bidirectional',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animationstep',
            name='repeat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
