# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BoardField')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='boardfield',
            name='income',
            field=models.ManyToManyField(through='api.FieldIncome', to='api.Resource'),
        ),
    ]
