# Generated by Django 2.1.1 on 2020-05-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200417_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='pass_to_children',
            field=models.TextField(blank=True, null=True),
        ),
    ]
