# Generated by Django 2.1.1 on 2019-08-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190817_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_choices', to='api.Keyword'),
        ),
    ]
