# Generated by Django 2.1.1 on 2019-09-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190929_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='height',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='opacity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='rotation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='stroke_thickness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='width',
            field=models.TextField(blank=True, null=True),
        ),
    ]
