# Generated by Django 2.1.1 on 2020-05-07 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_slot_pass_to_children'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stage',
            new_name='Widget',
        ),
        migrations.CreateModel(
            name='WidgetFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.TextField(blank=True, null=True)),
                ('style_inline', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_widgetframes', to='api.ImageAsset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='stageframe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='stageframe',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='stageframe',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='choiceframe',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='conditionframe',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='tokenframe',
            name='stage',
        ),
        migrations.AddField(
            model_name='choiceframe',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widget_choiceframes', to='api.Widget'),
        ),
        migrations.AddField(
            model_name='conditionframe',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widget_conditionframes', to='api.Widget'),
        ),
        migrations.AddField(
            model_name='tokenframe',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widget_tokenframes', to='api.Widget'),
        ),
        migrations.DeleteModel(
            name='StageFrame',
        ),
        migrations.AddField(
            model_name='widgetframe',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='api.Widget'),
        ),
        migrations.AddField(
            model_name='widgetframe',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widget_widgetframes', to='api.Widget'),
        ),
    ]
