# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20171122_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardfield',
            name='income',
            field=models.ManyToManyField(related_name='income', through='api.FieldIncome', to='api.Resource'),
        ),
    ]
