# Generated by Django 2.1.1 on 2018-10-25 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20181022_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.TextField(choices=[('AND', 'AND'), ('OR', 'OR'), ('NOT', 'NOT')], default='AND')),
            ],
        ),
        migrations.RemoveField(
            model_name='conditionclause',
            name='at_keyword_round',
        ),
        migrations.RemoveField(
            model_name='conditionclause',
            name='at_round',
        ),
        migrations.RemoveField(
            model_name='conditionclause',
            name='by_keyword_round',
        ),
        migrations.RemoveField(
            model_name='conditionclause',
            name='by_round',
        ),
        migrations.RemoveField(
            model_name='effectstack',
            name='action',
        ),
        migrations.RemoveField(
            model_name='effectstack',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='effectstack',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='action_limit',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='resource_limit',
        ),
        migrations.RemoveField(
            model_name='token',
            name='action_limit',
        ),
        migrations.RemoveField(
            model_name='token',
            name='resource_limit',
        ),
        migrations.AddField(
            model_name='conditionclause',
            name='relation',
            field=models.TextField(choices=[('AND', 'AND'), ('OR', 'OR'), ('NOT', 'NOT')], default='AND'),
        ),
        migrations.AddField(
            model_name='poolitem',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Choice'),
        ),
        migrations.AlterField(
            model_name='action',
            name='mode',
            field=models.CharField(choices=[('TRAP', 'TRAP'), ('TRIGGER', 'TRIGGER'), ('HYBRID', 'HYBRID'), ('AUTO', 'AUTO')], default='TRAP', max_length=255),
        ),
        migrations.AlterField(
            model_name='faction',
            name='type',
            field=models.CharField(choices=[('PLAYER', 'PLAYER'), ('BOT', 'BOT')], default='PLAYER', max_length=255),
        ),
        migrations.AddField(
            model_name='stackitem',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Action'),
        ),
        migrations.AddField(
            model_name='stackitem',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Choice'),
        ),
        migrations.AddField(
            model_name='stackitem',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Condition'),
        ),
        migrations.AddField(
            model_name='stackitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EffectStack'),
        ),
    ]
