# Generated by Django 2.1.1 on 2019-08-17 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_choice_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ImageAsset')),
                ('keywords', models.ManyToManyField(blank=True, related_name='keywords_choicetips', to='api.Keyword')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='choice',
            name='random',
        ),
        migrations.AddField(
            model_name='choice',
            name='chances',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice_chances', to='api.Expression'),
        ),
        migrations.AddField(
            model_name='choice',
            name='options_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice_options_filter', to='api.Expression'),
        ),
        migrations.AddField(
            model_name='choice',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice_time', to='api.Expression'),
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keywords_choiceoptions', to='api.Keyword'),
        ),
        migrations.AddField(
            model_name='choicetip',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='api.Choice'),
        ),
    ]
