# Generated by Django 2.1.1 on 2018-10-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20181025_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='rule_mode',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
