# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20171124_0917'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mappath',
            unique_together=set([]),
        ),
    ]
