# Generated by Django 2.1.1 on 2019-08-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190817_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='image',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='image',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='image',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='image',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='setups',
        ),
        migrations.RemoveField(
            model_name='field',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='field',
            name='image',
        ),
        migrations.RemoveField(
            model_name='field',
            name='risk',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='image',
        ),
        migrations.RemoveField(
            model_name='path',
            name='disable',
        ),
        migrations.RemoveField(
            model_name='path',
            name='enable',
        ),
        migrations.RemoveField(
            model_name='path',
            name='image',
        ),
        migrations.RemoveField(
            model_name='path',
            name='setups',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='image',
        ),
        migrations.RemoveField(
            model_name='round',
            name='image',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='image',
        ),
        migrations.RemoveField(
            model_name='state',
            name='image',
        ),
        migrations.RemoveField(
            model_name='style',
            name='image',
        ),
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
        migrations.RemoveField(
            model_name='team',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='token',
            name='image',
        ),
        migrations.AddField(
            model_name='state',
            name='frame',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
