# Generated by Django 2.1.1 on 2019-10-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190930_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='enabled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Expression'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='animation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animation', to='api.Animation'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sound', to='api.Sound'),
        ),
    ]
