# Generated by Django 2.1.1 on 2020-05-07 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200507_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('preload', models.TextField(blank=True, null=True)),
                ('load_done', models.TextField(blank=True, null=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_modules', to='api.Widget')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='phase',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='round',
            name='board',
        ),
        migrations.RemoveField(
            model_name='round',
            name='game',
        ),
        migrations.RemoveField(
            model_name='round',
            name='loader',
        ),
        migrations.RemoveField(
            model_name='roundslot',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='roundslot',
            name='round',
        ),
        migrations.AddField(
            model_name='game',
            name='get_active_module',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Phase',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.DeleteModel(
            name='RoundSlot',
        ),
        migrations.AddField(
            model_name='module',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game'),
        ),
        migrations.AddField(
            model_name='module',
            name='loader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Widget'),
        ),
    ]
