# Generated by Django 2.1.1 on 2018-10-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_condition_rule_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='effectstack',
            name='pick',
            field=models.CharField(choices=[('RANDOM', 'RANDOM'), ('CHOICE', 'CHOICE')], default='RANDOM', max_length=255),
        ),
    ]
