# Generated by Django 2.1.1 on 2020-05-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200508_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='game',
        ),
        migrations.RemoveField(
            model_name='action',
            name='template',
        ),
        migrations.RemoveField(
            model_name='actionconfig',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='actionparam',
            name='owner',
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='ActionConfig',
        ),
        migrations.DeleteModel(
            name='ActionParam',
        ),
    ]
