# Generated by Django 2.1.1 on 2019-10-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_slot_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='bidirectional',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animation',
            name='delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animation',
            name='repeat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
