# Generated by Django 2.1.1 on 2020-05-25 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200511_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=255)),
                ('global_state', models.TextField(blank=True, null=True)),
                ('own_data', models.TextField(blank=True, null=True)),
                ('on_init', models.TextField(blank=True, null=True)),
                ('preload', models.TextField(blank=True, null=True)),
                ('load_done', models.TextField(blank=True, null=True)),
                ('from_parent', models.TextField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Module')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.WidgetNode')),
                ('widget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Widget')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
