# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20171124_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardfield',
            name='income',
            field=models.ManyToManyField(blank=True, related_name='income', through='api.FieldIncome', to='api.Resource'),
        ),
    ]
