# Generated by Django 2.1.1 on 2019-10-12 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191011_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ImageAsset')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='api.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='animation',
            name='repeat',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='animationstep',
            name='repeat',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
