# Generated by Django 2.1.1 on 2020-05-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_sandbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandbox',
            name='type',
        ),
    ]
