# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20171124_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardfield',
            name='income',
            field=models.ManyToManyField(blank=True, through='api.FieldIncome', to='api.Resource'),
        ),
        migrations.AlterField(
            model_name='fieldincome',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
