# Generated by Django 2.1.1 on 2018-10-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20181025_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionconfig',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
