# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20171128_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldincome',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
