# Generated by Django 2.1.1 on 2019-10-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_text_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='description',
        ),
    ]
