# Generated by Django 2.1.1 on 2018-10-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20181025_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='restriction',
        ),
        migrations.AddField(
            model_name='action',
            name='allowed',
            field=models.ManyToManyField(blank=True, null=True, related_name='action_allowed', to='api.Stack'),
        ),
        migrations.AddField(
            model_name='action',
            name='restricted',
            field=models.ManyToManyField(blank=True, null=True, related_name='action_restricted', to='api.Stack'),
        ),
        migrations.AddField(
            model_name='actionconfig',
            name='max_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='actionconfig',
            name='min_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='actionconfig',
            name='random_amount',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actionconfig',
            name='target',
            field=models.CharField(choices=[('PLAYER', 'PLAYER'), ('OTHER_PLAYER', 'OTHER_PLAYER'), ('SELF', 'SELF'), ('ACTIVE_PLAYER', 'ACTIVE_PLAYER'), ('FACTION', 'FACTION'), ('KEYWORD', 'KEYWORD'), ('TOKEN', 'TOKEN'), ('ACTIVE_TOKEN', 'ACTIVE_TOKEN'), ('OTHER_TOKEN', 'OTHER_TOKEN')], max_length=255),
        ),
        migrations.AlterField(
            model_name='actionconfig',
            name='type',
            field=models.CharField(choices=[('MOVE', 'MOVE'), ('WIN_GAME', 'WIN_GAME'), ('LOSE_GAME', 'LOSE_GAME'), ('ALTER', 'ALTER'), ('DRAW', 'DRAW'), ('REDIRECT', 'REDIRECT'), ('DROP', 'DROP'), ('LOAD', 'LOAD'), ('GAMBLE', 'GAMBLE')], max_length=255),
        ),
    ]
