# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20171128_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldincome',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
