# Generated by Django 2.1.1 on 2018-10-27 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20181027_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionconfig',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_token', to='api.Token'),
        ),
    ]
