# Generated by Django 2.1.1 on 2019-10-12 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_text_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.Text'),
        ),
    ]
