# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20171128_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldincome',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
