# Generated by Django 2.1.1 on 2018-10-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_actionconfig_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionconfig',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionconfig',
            name='type',
            field=models.CharField(choices=[('MOVE', 'MOVE'), ('WIN_GAME', 'WIN_GAME'), ('LOSE_GAME', 'LOSE_GAME'), ('ALTER_RESOURCE', 'ALTER_RESOURCE'), ('DRAW', 'DRAW'), ('REDIRECT', 'REDIRECT'), ('DROP', 'DROP'), ('LOAD', 'LOAD'), ('GAMBLE', 'GAMBLE'), ('ALTER_KEYWORDS', 'ALTER_KEYWORDS')], max_length=255),
        ),
    ]
