# Generated by Django 2.1.1 on 2019-10-21 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20191012_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sonata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.TextField()),
                ('loop', models.NullBooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
            ],
        ),
        migrations.CreateModel(
            name='SonataStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(blank=True, null=True)),
                ('loop', models.NullBooleanField()),
                ('rate', models.FloatField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.Sonata')),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sound')),
            ],
        ),
        migrations.RemoveField(
            model_name='field',
            name='board',
        ),
        migrations.RemoveField(
            model_name='field',
            name='fails',
        ),
        migrations.RemoveField(
            model_name='field',
            name='game',
        ),
        migrations.RemoveField(
            model_name='field',
            name='passes',
        ),
        migrations.RemoveField(
            model_name='path',
            name='field',
        ),
        migrations.RemoveField(
            model_name='slotitem',
            name='field',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
