# Generated by Django 2.1.1 on 2018-10-28 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20181027_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conditionclause',
            old_name='keyword',
            new_name='keywords',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='restriction',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='rule_mode',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='trap_mode',
        ),
        migrations.AddField(
            model_name='condition',
            name='allowed',
            field=models.ManyToManyField(blank=True, null=True, related_name='condition_allowed', to='api.Stack'),
        ),
        migrations.AddField(
            model_name='condition',
            name='mode',
            field=models.CharField(choices=[('TRAP', 'TRAP'), ('TRIGGER', 'TRIGGER'), ('HYBRID', 'HYBRID'), ('AUTO', 'AUTO')], default='TRIGGER', max_length=255),
        ),
        migrations.AddField(
            model_name='condition',
            name='restricted',
            field=models.ManyToManyField(related_name='condition_restricted', to='api.Stack'),
        ),
        migrations.AddField(
            model_name='conditionclause',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause_choice', to='api.Choice'),
        ),
        migrations.AddField(
            model_name='conditionclause',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause_faction', to='api.Faction'),
        ),
        migrations.AddField(
            model_name='conditionclause',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause_round', to='api.Round'),
        ),
        migrations.AddField(
            model_name='conditionclause',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause_token', to='api.Token'),
        ),
        migrations.AlterField(
            model_name='conditionclause',
            name='type',
            field=models.CharField(choices=[('CLAIM', 'CLAIM'), ('REACH', 'REACH'), ('MEET', 'MEET'), ('AVOID', 'AVOID'), ('COMPLETE', 'COMPLETE'), ('PLAY', 'PLAY'), ('PLAY_MAX', 'PLAY_MAX'), ('HAVE', 'HAVE'), ('HAVE_MAX', 'HAVE_MAX'), ('HAVE_MORE', 'HAVE_MORE'), ('HAVE_LESS', 'HAVE_LESS'), ('IS', 'IS'), ('IS_BEFORE', 'IS_BEFORE'), ('IS_AFTER', 'IS_AFTER')], max_length=255),
        ),
    ]
