# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20171128_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='boardfield',
            name='income',
            field=models.ManyToManyField(blank=True, related_name='_income', through='api.FieldIncome', to='api.Resource'),
        ),
        migrations.AddField(
            model_name='fieldcost',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_cost', to='api.BoardField'),
        ),
        migrations.AddField(
            model_name='fieldcost',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Resource'),
        ),
        migrations.AddField(
            model_name='boardfield',
            name='cost',
            field=models.ManyToManyField(blank=True, related_name='_cost', through='api.FieldCost', to='api.Resource'),
        ),
    ]
