# Generated by Django 2.1.1 on 2019-10-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_handler_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='style_inline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='style_inline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
