# Generated by Django 2.1.1 on 2018-10-28 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20181028_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_stage', to='api.Stage'),
        ),
    ]
