# Generated by Django 2.1.1 on 2018-10-28 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_condition_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionclause',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause_stage', to='api.Stage'),
        ),
    ]
