# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20171201_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactionIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_income', to='api.Faction')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='faction',
            name='income',
            field=models.ManyToManyField(blank=True, related_name='faction_income', through='api.FactionIncome', to='api.Resource'),
        ),
    ]
