# Generated by Django 2.1.1 on 2019-11-03 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_shape_shapepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_shapes', to='api.Style'),
        ),
        migrations.AddField(
            model_name='shape',
            name='style_inline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
