# Generated by Django 2.1.1 on 2018-10-28 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_conditionclause_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionclause',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='api.Condition'),
        ),
    ]
