# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_action_actionconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionconfig',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='api.Action'),
        ),
    ]
