# Generated by Django 2.1.1 on 2019-11-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20191103_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Shape'),
        ),
    ]
