# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180106_1548'),
    ]

    operations = [
        migrations.RenameField('ActionConfig', 'bonus', 'amount')
    ]
