# Generated by Django 2.1.1 on 2018-10-29 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20181028_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='token',
            name='effect_pool',
        ),
        migrations.RemoveField(
            model_name='token',
            name='owner',
        ),
        migrations.AddField(
            model_name='phase',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='token',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
