# Generated by Django 2.1.1 on 2018-10-30 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20181029_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='options',
        ),
        migrations.RemoveField(
            model_name='poolitem',
            name='restriction',
        ),
        migrations.RemoveField(
            model_name='round',
            name='order',
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='round_order',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poolitem',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Resource'),
        ),
        migrations.AddField(
            model_name='poolitem',
            name='restricted',
            field=models.ManyToManyField(related_name='_poolitem_restricted_+', to='api.Stack'),
        ),
        migrations.AddField(
            model_name='poolitem',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Token'),
        ),
        migrations.AddField(
            model_name='round',
            name='phase_order',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='phases',
            field=models.ManyToManyField(related_name='_round_phases_+', to='api.Phase'),
        ),
        migrations.AddField(
            model_name='round',
            name='repeat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stackitem',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Resource'),
        ),
        migrations.AddField(
            model_name='stackitem',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Token'),
        ),
        migrations.AddField(
            model_name='token',
            name='allowed',
            field=models.ManyToManyField(related_name='_token_allowed_+', to='api.Stack'),
        ),
        migrations.AddField(
            model_name='token',
            name='effect_pool',
            field=models.ManyToManyField(related_name='_token_effect_pool_+', to='api.Pool'),
        ),
        migrations.AddField(
            model_name='token',
            name='restricted',
            field=models.ManyToManyField(related_name='_token_restricted_+', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='action',
            name='allowed',
            field=models.ManyToManyField(blank=True, related_name='action_allowed', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='action',
            name='condition',
            field=models.ManyToManyField(blank=True, related_name='action_condition', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='action',
            name='cost',
            field=models.ManyToManyField(blank=True, related_name='action_cost', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='action',
            name='restricted',
            field=models.ManyToManyField(blank=True, related_name='action_restricted', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='effect',
            field=models.ManyToManyField(related_name='_choiceoption_effect_+', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice.option.owner+', to='api.Choice'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='allowed',
            field=models.ManyToManyField(blank=True, related_name='_condition_allowed_+', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='award',
            field=models.ManyToManyField(related_name='_condition_award_+', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='mode',
            field=models.CharField(choices=[('TRAP', 'TRAP'), ('TRIGGER', 'TRIGGER'), ('HYBRID', 'HYBRID'), ('PASSIVE', 'PASSIVE'), ('AUTO', 'AUTO')], default='TRIGGER', max_length=255),
        ),
        migrations.AlterField(
            model_name='condition',
            name='penalty',
            field=models.ManyToManyField(related_name='_condition_penalty_+', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='restricted',
            field=models.ManyToManyField(related_name='_condition_restricted_+', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition.stage+', to='api.Stage'),
        ),
        migrations.AlterField(
            model_name='conditionclause',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause.action+', to='api.Action'),
        ),
        migrations.AlterField(
            model_name='conditionclause',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause.choice+', to='api.Choice'),
        ),
        migrations.AlterField(
            model_name='conditionclause',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause.condition+', to='api.Condition'),
        ),
        migrations.AlterField(
            model_name='conditionclause',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause.faction+', to='api.Faction'),
        ),
        migrations.AlterField(
            model_name='conditionclause',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause.field+', to='api.Field'),
        ),
        migrations.AlterField(
            model_name='conditionclause',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause.round+', to='api.Round'),
        ),
        migrations.AlterField(
            model_name='conditionclause',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause.stage+', to='api.Stage'),
        ),
        migrations.AlterField(
            model_name='conditionclause',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause.token+', to='api.Token'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='effect_pool',
            field=models.ManyToManyField(related_name='_faction_effect_pool_+', to='api.Pool'),
        ),
        migrations.AlterField(
            model_name='location',
            name='field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Field'),
        ),
        migrations.AlterField(
            model_name='poolitem',
            name='cost',
            field=models.ManyToManyField(related_name='_poolitem_cost_+', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='round',
            name='award',
            field=models.ManyToManyField(related_name='_round_award_+', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='round',
            name='condition',
            field=models.ManyToManyField(related_name='_round_condition_+', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='round',
            name='effect_pool',
            field=models.ManyToManyField(related_name='_round_effect_pool_+', to='api.Pool'),
        ),
        migrations.AlterField(
            model_name='round',
            name='penalty',
            field=models.ManyToManyField(related_name='_round_penalty_+', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='round',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='round.stage+', to='api.Stage'),
        ),
        migrations.AlterField(
            model_name='stackitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack.owner+', to='api.Stack'),
        ),
    ]
