# Generated by Django 2.1.1 on 2019-11-12 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_slot_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu', to='api.Stage'),
        ),
    ]
