# Generated by Django 2.1.1 on 2019-11-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_game_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionframe',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_actionframes', to='api.Stage'),
        ),
        migrations.AddField(
            model_name='actionframe',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_actionframes', to='api.Style'),
        ),
        migrations.AddField(
            model_name='actionframe',
            name='style_inline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choiceframe',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_choiceframes', to='api.Stage'),
        ),
        migrations.AddField(
            model_name='choiceframe',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_choiceframes', to='api.Style'),
        ),
        migrations.AddField(
            model_name='choiceframe',
            name='style_inline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conditionframe',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_conditionframes', to='api.Stage'),
        ),
        migrations.AddField(
            model_name='conditionframe',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_conditionframes', to='api.Style'),
        ),
        migrations.AddField(
            model_name='conditionframe',
            name='style_inline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slotframe',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_slotframes', to='api.Stage'),
        ),
        migrations.AddField(
            model_name='slotframe',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_slotframes', to='api.Style'),
        ),
        migrations.AddField(
            model_name='slotframe',
            name='style_inline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenframe',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_tokenframes', to='api.Stage'),
        ),
        migrations.AddField(
            model_name='tokenframe',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='style_tokenframes', to='api.Style'),
        ),
        migrations.AddField(
            model_name='tokenframe',
            name='style_inline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionframe',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_actionframes', to='api.ImageAsset'),
        ),
        migrations.AlterField(
            model_name='choiceframe',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_choiceframes', to='api.ImageAsset'),
        ),
        migrations.AlterField(
            model_name='conditionframe',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_conditionframes', to='api.ImageAsset'),
        ),
        migrations.AlterField(
            model_name='slotframe',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_slotframes', to='api.ImageAsset'),
        ),
        migrations.AlterField(
            model_name='tokenframe',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_tokenframes', to='api.ImageAsset'),
        ),
    ]
