# Generated by Django 2.1.1 on 2018-10-30 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20181030_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='allowed',
            field=models.ManyToManyField(blank=True, related_name='_choice_allowed_+', to='api.Stack'),
        ),
        migrations.AddField(
            model_name='choice',
            name='condition',
            field=models.ManyToManyField(blank=True, related_name='_choice_condition_+', to='api.Stack'),
        ),
        migrations.AddField(
            model_name='choice',
            name='cost',
            field=models.ManyToManyField(blank=True, related_name='_choice_cost_+', to='api.Stack'),
        ),
        migrations.AddField(
            model_name='choice',
            name='mode',
            field=models.CharField(choices=[('TRAP', 'TRAP'), ('TRIGGER', 'TRIGGER'), ('HYBRID', 'HYBRID'), ('AUTO', 'AUTO')], default='TRAP', max_length=255),
        ),
        migrations.AddField(
            model_name='choice',
            name='restricted',
            field=models.ManyToManyField(blank=True, related_name='_choice_restricted_+', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='action',
            name='allowed',
            field=models.ManyToManyField(blank=True, related_name='_action_allowed_+', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='action',
            name='condition',
            field=models.ManyToManyField(blank=True, related_name='_action_condition_+', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='action',
            name='cost',
            field=models.ManyToManyField(blank=True, related_name='_action_cost_+', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='action',
            name='restricted',
            field=models.ManyToManyField(blank=True, related_name='_action_restricted_+', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='actionconfig',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action.config.action+', to='api.Action'),
        ),
        migrations.AlterField(
            model_name='actionconfig',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action.choice+', to='api.Choice'),
        ),
        migrations.AlterField(
            model_name='actionconfig',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action.condition+', to='api.Condition'),
        ),
        migrations.AlterField(
            model_name='actionconfig',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action.faction+', to='api.Faction'),
        ),
        migrations.AlterField(
            model_name='actionconfig',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action.resource+', to='api.Resource'),
        ),
        migrations.AlterField(
            model_name='actionconfig',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action.token+', to='api.Token'),
        ),
    ]
