# Generated by Django 2.1.1 on 2019-11-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20191117_1635'),
        ('api', '0029_slot_shape'),
    ]

    operations = [
    ]
