# Generated by Django 2.1.1 on 2018-10-30 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20181030_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceoption',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_option_owner', to='api.Choice'),
        ),
    ]
