# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20180117_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, max_length=200, null=True, upload_to='quest_images')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
            ],
        ),
        migrations.CreateModel(
            name='QuestAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('minAmount', models.IntegerField(blank=True, null=True)),
                ('maxAmount', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestPenalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('minAmount', models.IntegerField(blank=True, null=True)),
                ('maxAmount', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='image',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='action_images'),
        ),
        migrations.AddField(
            model_name='questpenalty',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_pen_action', to='api.Action'),
        ),
        migrations.AddField(
            model_name='questpenalty',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_pen_field', to='api.BoardField'),
        ),
        migrations.AddField(
            model_name='questpenalty',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_penalty', to='api.Quest'),
        ),
        migrations.AddField(
            model_name='questpenalty',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_penalty_quest', to='api.Quest'),
        ),
        migrations.AddField(
            model_name='questpenalty',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_pen_resource', to='api.Resource'),
        ),
        migrations.AddField(
            model_name='questcost',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_cost_action', to='api.Action'),
        ),
        migrations.AddField(
            model_name='questcost',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_cost_field', to='api.BoardField'),
        ),
        migrations.AddField(
            model_name='questcost',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_cost', to='api.Quest'),
        ),
        migrations.AddField(
            model_name='questcost',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_cost_quest', to='api.Quest'),
        ),
        migrations.AddField(
            model_name='questcost',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_cost_resource', to='api.Resource'),
        ),
        migrations.AddField(
            model_name='questcondition',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_condition_action', to='api.Action'),
        ),
        migrations.AddField(
            model_name='questcondition',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_cond_field', to='api.BoardField'),
        ),
        migrations.AddField(
            model_name='questcondition',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_condition', to='api.Quest'),
        ),
        migrations.AddField(
            model_name='questcondition',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_condition_quest', to='api.Quest'),
        ),
        migrations.AddField(
            model_name='questcondition',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_cond_resource', to='api.Resource'),
        ),
        migrations.AddField(
            model_name='questaward',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_award_action', to='api.Action'),
        ),
        migrations.AddField(
            model_name='questaward',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_award_field', to='api.BoardField'),
        ),
        migrations.AddField(
            model_name='questaward',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_award', to='api.Quest'),
        ),
        migrations.AddField(
            model_name='questaward',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_award_quest', to='api.Quest'),
        ),
        migrations.AddField(
            model_name='questaward',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_award_resource', to='api.Resource'),
        ),
    ]
