# Generated by Django 2.1.1 on 2019-11-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_token_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotitem',
            name='action',
        ),
        migrations.RemoveField(
            model_name='slotitem',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='slotitem',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='slotitem',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='slotitem',
            name='token',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='state',
        ),
        migrations.AddField(
            model_name='slot',
            name='item',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SlotItem',
        ),
    ]
