# Generated by Django 2.1.1 on 2019-11-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20191119_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='state',
        ),
        migrations.RemoveField(
            model_name='token',
            name='value',
        ),
    ]
