# Generated by Django 2.1.1 on 2018-10-30 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20181030_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='allowed',
            field=models.ManyToManyField(blank=True, related_name='action_allowed', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='action',
            name='condition',
            field=models.ManyToManyField(blank=True, related_name='action_condition', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='action',
            name='cost',
            field=models.ManyToManyField(blank=True, related_name='action_cost', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='action',
            name='restricted',
            field=models.ManyToManyField(blank=True, related_name='action_restricted', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='actionconfig',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_config_action', to='api.Action'),
        ),
        migrations.AlterField(
            model_name='actionconfig',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Choice'),
        ),
        migrations.AlterField(
            model_name='actionconfig',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Condition'),
        ),
        migrations.AlterField(
            model_name='actionconfig',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Faction'),
        ),
        migrations.AlterField(
            model_name='actionconfig',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Resource'),
        ),
        migrations.AlterField(
            model_name='actionconfig',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Token'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='allowed',
            field=models.ManyToManyField(blank=True, related_name='choice_allowed', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='condition',
            field=models.ManyToManyField(blank=True, related_name='choice_condition', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='cost',
            field=models.ManyToManyField(blank=True, related_name='choice_cost', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='restricted',
            field=models.ManyToManyField(blank=True, related_name='choice_restricted', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='effect',
            field=models.ManyToManyField(to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='allowed',
            field=models.ManyToManyField(blank=True, related_name='condition_allowed', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='award',
            field=models.ManyToManyField(related_name='condition_award', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='penalty',
            field=models.ManyToManyField(related_name='condition_penalty', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='restricted',
            field=models.ManyToManyField(related_name='condition_restricted', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Stage'),
        ),
        migrations.AlterField(
            model_name='conditionclause',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Action'),
        ),
        migrations.AlterField(
            model_name='conditionclause',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Choice'),
        ),
        migrations.AlterField(
            model_name='conditionclause',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clause_condition', to='api.Condition'),
        ),
        migrations.AlterField(
            model_name='conditionclause',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Faction'),
        ),
        migrations.AlterField(
            model_name='conditionclause',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Field'),
        ),
        migrations.AlterField(
            model_name='conditionclause',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Round'),
        ),
        migrations.AlterField(
            model_name='conditionclause',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Stage'),
        ),
        migrations.AlterField(
            model_name='conditionclause',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Token'),
        ),
    ]
