# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20180124_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questaward',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_award_action', to='api.Action'),
        ),
        migrations.AlterField(
            model_name='questaward',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_award_quest', to='api.Quest'),
        ),
        migrations.AlterField(
            model_name='questcondition',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_condition_action', to='api.Action'),
        ),
        migrations.AlterField(
            model_name='questcondition',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_condition_quest', to='api.Quest'),
        ),
        migrations.AlterField(
            model_name='questcost',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_cost_action', to='api.Action'),
        ),
        migrations.AlterField(
            model_name='questcost',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_cost_quest', to='api.Quest'),
        ),
        migrations.AlterField(
            model_name='questpenalty',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_pen_action', to='api.Action'),
        ),
        migrations.AlterField(
            model_name='questpenalty',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_pen_quest', to='api.Quest'),
        ),
    ]
