# Generated by Django 2.1.1 on 2018-10-30 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20181030_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_owner', to='api.Stack'),
        ),
    ]
