# Generated by Django 2.1.1 on 2019-11-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20191122_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionconfig',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='actionconfig',
            name='target',
        ),
        migrations.RemoveField(
            model_name='actionconfig',
            name='value',
        ),
        migrations.AddField(
            model_name='actionconfig',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
