# Generated by Django 2.1.1 on 2019-11-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20191130_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='display_name',
        ),
        migrations.AddField(
            model_name='slothandler',
            name='handler_inline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
