# Generated by Django 2.1.1 on 2018-10-30 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20181030_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='choice_images'),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='choice_option_images'),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.Choice'),
        ),
    ]
