# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20180130_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='questcondition',
            name='atRound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_cond_atRound', to='api.Round'),
        ),
        migrations.AddField(
            model_name='questcondition',
            name='byRound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_cond_byRound', to='api.Round'),
        ),
    ]
