# Generated by Django 2.1.1 on 2019-11-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20191130_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slothandler',
            name='handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Handler'),
        ),
    ]
