# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20180131_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Action')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_action', to='api.Round')),
            ],
        ),
        migrations.CreateModel(
            name='RoundQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Quest')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_quest', to='api.Round')),
            ],
        ),
    ]
