# Generated by Django 2.1.1 on 2019-11-30 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0004_remove_gameplayer_team'),
        ('api', '0038_auto_20191130_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handler',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='game',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='sound',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='state',
        ),
        migrations.RemoveField(
            model_name='state',
            name='animation',
        ),
        migrations.RemoveField(
            model_name='state',
            name='game',
        ),
        migrations.RemoveField(
            model_name='state',
            name='sound',
        ),
        migrations.RemoveField(
            model_name='state',
            name='style',
        ),
        migrations.RemoveField(
            model_name='team',
            name='board',
        ),
        migrations.RemoveField(
            model_name='team',
            name='game',
        ),
        migrations.RenameField(
            model_name='slothandler',
            old_name='handler_inline',
            new_name='effect_inline',
        ),
        migrations.RemoveField(
            model_name='slothandler',
            name='handler',
        ),
        migrations.AddField(
            model_name='slothandler',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Expression'),
        ),
        migrations.AddField(
            model_name='slothandler',
            name='sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handler_sound', to='api.Expression'),
        ),
        migrations.AddField(
            model_name='slothandler',
            name='sound_inline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slothandler',
            name='type',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Handler',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
