# Generated by Django 2.1.1 on 2018-11-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20181030_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='team_images')),
                ('min_players', models.IntegerField(default=1)),
                ('max_players', models.IntegerField(default=1)),
                ('effect_pool', models.ManyToManyField(blank=True, related_name='team_effect_pool', to='api.Pool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='field',
            name='stage',
        ),
        migrations.AddField(
            model_name='game',
            name='fixed_teams',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='round_cycles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='effect_pool',
            field=models.ManyToManyField(blank=True, related_name='faction_effect_pool', to='api.Pool'),
        ),
        migrations.AlterField(
            model_name='field',
            name='award',
            field=models.ManyToManyField(blank=True, related_name='field_award', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='field',
            name='cost',
            field=models.ManyToManyField(blank=True, related_name='field_cost', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='field',
            name='effect_pool',
            field=models.ManyToManyField(blank=True, related_name='field_effect_pool', to='api.Pool'),
        ),
        migrations.AlterField(
            model_name='field',
            name='penalty',
            field=models.ManyToManyField(blank=True, related_name='field_penalty', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='token',
            name='allowed',
            field=models.ManyToManyField(blank=True, related_name='token_allowed', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='token',
            name='effect_pool',
            field=models.ManyToManyField(blank=True, related_name='token_effect_pool', to='api.Pool'),
        ),
        migrations.AlterField(
            model_name='token',
            name='restricted',
            field=models.ManyToManyField(blank=True, related_name='token_restricted', to='api.Stack'),
        ),
        migrations.AddField(
            model_name='team',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game'),
        ),
    ]
