# Generated by Django 2.1.1 on 2018-11-01 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20181101_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolitem',
            name='cost',
            field=models.ManyToManyField(related_name='pool_item_cost', to='api.Stack'),
        ),
        migrations.AlterField(
            model_name='poolitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_items', to='api.Pool'),
        ),
        migrations.AlterField(
            model_name='poolitem',
            name='restricted',
            field=models.ManyToManyField(related_name='pool_item_restricted', to='api.Stack'),
        ),
    ]
