# Generated by Django 2.1.1 on 2019-11-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20191130_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='enabled',
        ),
        migrations.AddField(
            model_name='slot',
            name='display_text_inline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
