# Generated by Django 2.1.1 on 2019-12-01 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20191130_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animationstep',
            name='from_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_style', to='api.Style'),
        ),
        migrations.AlterField(
            model_name='animationstep',
            name='to_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_style', to='api.Style'),
        ),
    ]
