# Generated by Django 2.1.1 on 2018-11-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20181101_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolitem',
            name='allowed',
            field=models.ManyToManyField(related_name='pool_item_allowed', to='api.Stack'),
        ),
    ]
