# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_roundcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Action')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_activity', to='api.BoardField')),
            ],
        ),
        migrations.CreateModel(
            name='FieldQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_quest', to='api.BoardField')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Quest')),
            ],
        ),
    ]
