# Generated by Django 2.1.1 on 2019-12-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20191201_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='display_text_inline',
        ),
        migrations.AlterField(
            model_name='slot',
            name='display_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
