# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_fieldactivity_fieldquest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, max_length=200, null=True, upload_to='activity_images')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='RoundActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Activity')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_activity', to='api.Round')),
            ],
        ),
        migrations.RenameModel(
            old_name='ActionConfig',
            new_name='ActivityConfig',
        ),
        migrations.RemoveField(
            model_name='action',
            name='game',
        ),
        migrations.RemoveField(
            model_name='roundaction',
            name='action',
        ),
        migrations.RemoveField(
            model_name='roundaction',
            name='round',
        ),
        migrations.AlterModelOptions(
            name='fieldactivity',
            options={'verbose_name_plural': 'Field activities'},
        ),
        migrations.RemoveField(
            model_name='activityconfig',
            name='action',
        ),
        migrations.RemoveField(
            model_name='questaward',
            name='action',
        ),
        migrations.RemoveField(
            model_name='questcondition',
            name='action',
        ),
        migrations.RemoveField(
            model_name='questcost',
            name='action',
        ),
        migrations.RemoveField(
            model_name='questpenalty',
            name='action',
        ),
        migrations.AlterField(
            model_name='fieldactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Activity'),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='RoundAction',
        ),
        migrations.AddField(
            model_name='activityconfig',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='config', to='api.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questaward',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_award_activity', to='api.Activity'),
        ),
        migrations.AddField(
            model_name='questcondition',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_condition_activity', to='api.Activity'),
        ),
        migrations.AddField(
            model_name='questcost',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_cost_activity', to='api.Activity'),
        ),
        migrations.AddField(
            model_name='questpenalty',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_pen_activity', to='api.Activity'),
        ),
    ]
