# Generated by Django 2.1.1 on 2018-11-01 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_poolitem_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.Pool'),
        ),
    ]
