# Generated by Django 2.1.1 on 2019-12-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20191201_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slothandler',
            name='effect_inline',
        ),
        migrations.AlterField(
            model_name='slothandler',
            name='effect',
            field=models.TextField(blank=True, null=True),
        ),
    ]
