# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20180201_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roundactivity',
            options={'verbose_name_plural': 'Round activities'},
        ),
    ]
