# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20180201_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='questaward',
            name='atRound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_award_atRound', to='api.Round'),
        ),
        migrations.AddField(
            model_name='questaward',
            name='byRound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_award_byRound', to='api.Round'),
        ),
        migrations.AddField(
            model_name='questpenalty',
            name='atRound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_pen_atRound', to='api.Round'),
        ),
        migrations.AddField(
            model_name='questpenalty',
            name='byRound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_pen_byRound', to='api.Round'),
        ),
    ]
