# Generated by Django 2.1.1 on 2019-12-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20191201_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slothandler',
            name='sound_inline',
        ),
        migrations.AlterField(
            model_name='slothandler',
            name='sound',
            field=models.TextField(blank=True, null=True),
        ),
    ]
