# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20180201_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questaward',
            name='atRound',
        ),
        migrations.RemoveField(
            model_name='questaward',
            name='byRound',
        ),
        migrations.RemoveField(
            model_name='questaward',
            name='field',
        ),
        migrations.RemoveField(
            model_name='questaward',
            name='maxAmount',
        ),
        migrations.RemoveField(
            model_name='questaward',
            name='minAmount',
        ),
        migrations.RemoveField(
            model_name='questaward',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='questaward',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='questaward',
            name='type',
        ),
        migrations.RemoveField(
            model_name='questcost',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='questcost',
            name='field',
        ),
        migrations.RemoveField(
            model_name='questcost',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='questcost',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='questcost',
            name='type',
        ),
        migrations.RemoveField(
            model_name='questpenalty',
            name='atRound',
        ),
        migrations.RemoveField(
            model_name='questpenalty',
            name='byRound',
        ),
        migrations.RemoveField(
            model_name='questpenalty',
            name='field',
        ),
        migrations.RemoveField(
            model_name='questpenalty',
            name='maxAmount',
        ),
        migrations.RemoveField(
            model_name='questpenalty',
            name='minAmount',
        ),
        migrations.RemoveField(
            model_name='questpenalty',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='questpenalty',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='questpenalty',
            name='type',
        ),
        migrations.AlterField(
            model_name='questaward',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_award_activity', to='api.Activity'),
        ),
        migrations.AlterField(
            model_name='questaward',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_award', to='api.Quest'),
        ),
        migrations.AlterField(
            model_name='questcost',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_cost_activity', to='api.Activity'),
        ),
        migrations.AlterField(
            model_name='questcost',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_cost', to='api.Quest'),
        ),
        migrations.AlterField(
            model_name='questpenalty',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_pen_activity', to='api.Activity'),
        ),
        migrations.AlterField(
            model_name='questpenalty',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_penalty', to='api.Quest'),
        ),
    ]
