# Generated by Django 2.1.1 on 2019-12-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20191201_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='style',
            field=models.TextField(blank=True, null=True),
        ),
    ]
