# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_trivia_triviaanswer_triviaanswereffect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaanswereffect',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_answer_effect', to='api.TriviaAnswer'),
        ),
    ]
