# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triviaanswer',
            name='name',
        ),
        migrations.AlterField(
            model_name='triviaanswer',
            name='description',
            field=models.TextField(),
        ),
    ]
