# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_boardfield_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplocation',
            name='stage',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.Stage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mappath',
            name='stage',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.Stage'),
            preserve_default=False,
        ),
    ]
