# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20180224_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactionTermination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Faction')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Quest')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalTermination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Termination',
        ),
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_players',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='recommended_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='globaltermination',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game'),
        ),
        migrations.AddField(
            model_name='globaltermination',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Quest'),
        ),
    ]
