# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0002_auto_20180311_0737'),
        ('api', '0054_auto_20180226_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='api_auth.AppUser'),
            preserve_default=False,
        ),
    ]
