# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_game_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Activity')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Resource')),
            ],
        ),
        migrations.AlterField(
            model_name='activityconfig',
            name='mode',
            field=models.CharField(choices=[('TRIGGER', 'TRIGGER'), ('AUTO_TRIGGER', 'AUTO_TRIGGER')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activityconfig',
            name='target',
            field=models.CharField(choices=[('FIELD', 'FIELD'), ('PLAYER', 'PLAYER'), ('OTHER_PLAYER', 'OTHER_PLAYER'), ('SELF', 'SELF'), ('ACTIVE_PLAYER', 'ACTIVE_PLAYER')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activityconfig',
            name='type',
            field=models.CharField(choices=[('MOVE', 'MOVE'), ('WIN_GAME', 'WIN_GAME'), ('LOSE_GAME', 'LOSE_GAME'), ('COLLECT_RESOURCES', 'COLLECT_RESOURCES'), ('ALTER_RESOURCE', 'ALTER_RESOURCE'), ('PREPARE_RESOURCE', 'PREPARE_RESOURCE'), ('STORE_RESOURCE', 'STORE_RESOURCE'), ('REQUEST_HINT', 'REQUEST_HINT'), ('GIVE_HINT', 'GIVE_HINT'), ('DRAW', 'DRAW')], max_length=255),
        ),
    ]
