# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-14 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_resource_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to='field_images')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='boardfield',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='boardfield',
            name='game',
        ),
        migrations.RemoveField(
            model_name='boardfield',
            name='income',
        ),
        migrations.RemoveField(
            model_name='boardfield',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='factiontermination',
            name='faction',
        ),
        migrations.RemoveField(
            model_name='factiontermination',
            name='quest',
        ),
        migrations.AddField(
            model_name='activity',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faction',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faction',
            name='type',
            field=models.CharField(choices=[('PLAYER', 'PLAYER'), ('BOT', 'BOT'), ('MASTER', 'MASTER')], default='PLAYER', max_length=255),
        ),
        migrations.AddField(
            model_name='quest',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='mode',
            field=models.CharField(choices=[('TRIGGER', 'TRIGGER'), ('PASSIVE', 'PASSIVE')], default='TRIGGER', max_length=255),
        ),
        migrations.AddField(
            model_name='questcondition',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='activity_images'),
        ),
        migrations.AlterField(
            model_name='activityconfig',
            name='mode',
            field=models.CharField(choices=[('TRIGGER', 'TRIGGER'), ('PASSIVE', 'PASSIVE')], max_length=255),
        ),
        migrations.AlterField(
            model_name='faction',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='faction_images'),
        ),
        migrations.AlterField(
            model_name='fieldactivity',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_activity', to='api.Field'),
        ),
        migrations.AlterField(
            model_name='fieldcost',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_cost', to='api.Field'),
        ),
        migrations.AlterField(
            model_name='fieldincome',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_income', to='api.Field'),
        ),
        migrations.AlterField(
            model_name='fieldquest',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_quest', to='api.Field'),
        ),
        migrations.AlterField(
            model_name='maplocation',
            name='field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Field'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='quest_images'),
        ),
        migrations.AlterField(
            model_name='questcondition',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_cond_field', to='api.Field'),
        ),
        migrations.AlterField(
            model_name='questcondition',
            name='type',
            field=models.CharField(choices=[('CLAIM', 'CLAIM'), ('REACH', 'REACH'), ('MEET', 'MEET'), ('AVOID', 'AVOID'), ('COMPLETE', 'COMPLETE'), ('TRIGGER', 'TRIGGER')], max_length=255),
        ),
        migrations.DeleteModel(
            name='BoardField',
        ),
        migrations.DeleteModel(
            name='FactionTermination',
        ),
        migrations.AddField(
            model_name='field',
            name='cost',
            field=models.ManyToManyField(blank=True, related_name='_cost', through='api.FieldCost', to='api.Resource'),
        ),
        migrations.AddField(
            model_name='field',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Game'),
        ),
        migrations.AddField(
            model_name='field',
            name='income',
            field=models.ManyToManyField(blank=True, related_name='_income', through='api.FieldIncome', to='api.Resource'),
        ),
        migrations.AddField(
            model_name='field',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Stage'),
        ),
        migrations.AddField(
            model_name='faction',
            name='start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Field'),
        ),
    ]
