# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-14 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20180414_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityconfig',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='activityconfig',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='activityconfig',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='activitycost',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='activitycost',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='activity',
            name='mode',
            field=models.CharField(choices=[('TRIGGER', 'TRIGGER'), ('PASSIVE', 'PASSIVE')], default='TRIGGER', max_length=255),
        ),
    ]
