# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-19 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20180414_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='trivia',
            name='mode',
        ),
        migrations.AddField(
            model_name='activityconfig',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_quest', to='api.Quest'),
        ),
        migrations.AddField(
            model_name='activityconfig',
            name='trivia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_trivia', to='api.Trivia'),
        ),
        migrations.AlterField(
            model_name='activityconfig',
            name='type',
            field=models.CharField(choices=[('MOVE', 'MOVE'), ('WIN_GAME', 'WIN_GAME'), ('LOSE_GAME', 'LOSE_GAME'), ('COLLECT_RESOURCES', 'COLLECT_RESOURCES'), ('ALTER_RESOURCE', 'ALTER_RESOURCE'), ('PREPARE_RESOURCE', 'PREPARE_RESOURCE'), ('STORE_RESOURCE', 'STORE_RESOURCE'), ('REQUEST_HINT', 'REQUEST_HINT'), ('GIVE_HINT', 'GIVE_HINT'), ('DRAW', 'DRAW'), ('TRIGGER_QUEST', 'TRIGGER_QUEST'), ('TRIGGER_TRIVIA', 'TRIGGER_TRIVIA')], max_length=255),
        ),
    ]
