# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-23 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20180423_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityconfig',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_faction', to='api.Faction'),
        ),
        migrations.AddField(
            model_name='activityconfig',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitycost',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activitycost',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='api.Activity'),
        ),
        migrations.AlterField(
            model_name='activitycost',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
