# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20180423_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activity_images'),
        ),
    ]
