# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20180425_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityconfig',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='api.Activity'),
        ),
        migrations.AlterField(
            model_name='activitycost',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='api.Activity'),
        ),
    ]
