# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20180425_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycost',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Resource'),
        ),
    ]
