# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20180501_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factionincome',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='factionincome',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='factionresource',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='factionresource',
            name='date_modified',
        ),
        migrations.AlterField(
            model_name='activityquota',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityquota',
            name='filter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activityquota',
            name='type',
            field=models.CharField(choices=[('DISTRIBUTED', 'DISTRIBUTED'), ('LIMITED', 'LIMITED')], default='DISTRIBUTED', max_length=255),
        ),
    ]
