# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20180501_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='income',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='resources',
        ),
    ]
