# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-01 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20180501_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questcondition',
            old_name='atRound',
            new_name='at_round',
        ),
        migrations.RenameField(
            model_name='questcondition',
            old_name='byRound',
            new_name='by_round',
        ),
        migrations.RenameField(
            model_name='questcondition',
            old_name='keywords',
            new_name='keyword',
        ),
        migrations.RemoveField(
            model_name='questaward',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='questaward',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='questcondition',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='questcondition',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='questpenalty',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='questpenalty',
            name='date_modified',
        ),
        migrations.AlterField(
            model_name='questcondition',
            name='type',
            field=models.CharField(choices=[('CLAIM', 'CLAIM'), ('REACH', 'REACH'), ('MEET', 'MEET'), ('AVOID', 'AVOID'), ('COMPLETE', 'COMPLETE'), ('TRIGGER', 'TRIGGER'), ('GATHER', 'GATHER')], max_length=255),
        ),
    ]
