# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-05 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20180501_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_stage', to='api.Stage'),
        ),
        migrations.AlterField(
            model_name='questaward',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='api.Quest'),
        ),
        migrations.AlterField(
            model_name='questcondition',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='api.Quest'),
        ),
        migrations.AlterField(
            model_name='questpenalty',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty', to='api.Quest'),
        ),
    ]
