# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-12 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20180505_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='quest_images'),
        ),
    ]
