# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-12 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20180512_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maplocation',
            old_name='left',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='maplocation',
            old_name='top',
            new_name='y',
        ),
        migrations.RemoveField(
            model_name='triviaanswer',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='triviaanswer',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='triviaanswereffect',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='triviaanswereffect',
            name='date_modified',
        ),
        migrations.AlterField(
            model_name='trivia',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='trivia_images'),
        ),
        migrations.AlterField(
            model_name='triviaanswer',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='trivia_answer_images'),
        ),
    ]
