# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20180512_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviaanswer',
            name='trivia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.Trivia'),
        ),
        migrations.AlterField(
            model_name='triviaanswereffect',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effect', to='api.TriviaAnswer'),
        ),
    ]
