# Generated by Django 2.1.1 on 2020-04-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayer',
            name='color',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='faction',
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
