# Generated by Django 2.1.1 on 2019-09-21 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_slot_populate_by'),
        ('arena', '0002_auto_20190913_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='setup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Setup'),
            preserve_default=False,
        ),
    ]
