# Generated by Django 2.1.1 on 2019-11-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_gameinstance_setup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayer',
            name='team',
        ),
    ]
